displayThisText(typeof abcdefg)
displayThisText(typeof true)
displayThisText(typeof 123456)
displayThisText(typeof 123456n)
displayThisText(typeof Symbol("foo"))
displayThisText(typeof null)
displayThisText(typeof displayThisText)
